# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/defaulter-dynamics',
                'doc_host': 'https://booleanhunter-tech-blog.github.io',
                'git_url': 'https://github.com/booleanhunter-tech-blog/defaulter-dynamics',
                'lib_path': 'defaulter_dynamics'},
  'syms': {'defaulter_dynamics.core': {'defaulter_dynamics.core.foo': ('core.html#foo', 'defaulter_dynamics/core.py')}}}
