# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data-cleaning-tutorial',
                'doc_host': 'https://booleanhunter-tech-blog.github.io',
                'git_url': 'https://github.com/booleanhunter-tech-blog/data-cleaning-tutorial',
                'lib_path': 'data_cleaning_tutorial'},
  'syms': {'data_cleaning_tutorial.core': {'data_cleaning_tutorial.core.foo': ('core.html#foo', 'data_cleaning_tutorial/core.py')}}}
