project:
  type: website

format:
  html:
    cover-image: data-galaxy.png
    theme:
      light: flatly
      dark: slate
    fontsize: 1.1em
    linestretch: 1.7
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  reader-mode: true
  navbar:
    background: dark
    search: true
  sidebar: false

metadata-files: [nbdev.yml]