project:
  type: website

format:
  html:
    cover-image: data-galaxy.png
    theme:
      light: flatly
      dark: slate
    fontsize: 1.1em
    linestretch: 1.7
    grid:
      margin-width: 325px
      body-width: 850px
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  reader-mode: true
  navbar:
    background: dark
    search: true
    left:
      - text: "About"
        href: "./about.ipynb"
  sidebar: false
  back-to-top-navigation: true

metadata-files: [nbdev.yml]